### ISSUE TITLE
Increment version number for all builds

### ISSUE THREAD

**Issue by jamesla** [cnring18/cordova-build-increment#5]
Is there any way to increment version numbers for all builds by default (IE cordova build rather than cordova build --inc-version)?

The reason I ask is because it would be difficult to get all team members to remember to add the --inc-version parameter to all builds since everyone is in the habit of just typing cordova build.

**Comment by sebastianovide** [comment]
what about using CI ?

**Comment by cnring18** [comment]
@jamesla I designed the hook initially for platform specific build numbers, that is why they are incremented by default. Incrementing the version number uses the --inc-version flag because it was not the initial function of the hook, but can be accomplished using the same code. Incrementing the version number by default would require a separate hook designed to do just that.
